### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by ChessGeekBoy** [ChessGeekBoy/flappy-bird#2]
# Dificulty
We should allow the player to choose a difficulty (Easy, Medium, Hard)
Here is an Enum as an example:
`
export enum Difficulty {
    Easy,
    Medium,
    Hard
}
`

**Comment by Spicy-Axolotl** [comment]
Yeah.

**Comment by ChessGeekBoy** [comment]
I've created the Difficulty enum

**Comment by ChessGeekBoy** [comment]
Let's keep this issue open until we have full functionality

**Comment by Spicy-Axolotl** [comment]
Alright, later when I build my arcade in C++, I'll convert it over to C++ from TypeScript.

**Comment by ChessGeekBoy** [comment]
To make the game easier to maintain, this feature will not be implemented.
