### ISSUE TITLE
Unknown property access for ClassDeclaration

### ISSUE THREAD

**Issue by Spicy-Axolotl** [ChessGeekBoy/flappy-bird#6]
When I try to run a function from a different class I get "error TS9237: Unknown property access for ClassDeclaration". I am importing classes with `gameEngine.TowerManager.prototype.generateTowers();` for instance. How can I properly import the class's functions?

**Comment by Spicy-Axolotl** [comment]
I found two resources, which might be helpful.
https://makecode.microbit.org/blocks/custom 
https://makecode.microbit.org/javascript/classes

**Comment by ChessGeekBoy** [comment]
# Static vs. Non-Static
Like Java, JavaScript (and TypeScript) have the concept of static vs non-static. Non-static properties are accessed through an object of the class type and accessed like this: `{object-name}{property-name}`. Static properties, however, are invoked like this: `{class-name}.{property-name}`

## Constructors
Objects need constructors. Here is how to invoke a constructor:
```
let {variable-name} [: {class-name}] = new {class-name}({constructor-parameters})
```

## Key
{} - Fill it in
[] - Optional
