### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Spicy-Axolotl** [ChessGeekBoy/flappy-bird#8]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/84357429/160713325-f700042c-d448-4801-ba8d-df761f4e048b.png">
Here is an image with the error.

**Comment by Spicy-Axolotl** [comment]
More errors I found.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/84357429/160726875-539a0fff-943c-463a-86d4-03ed10917d47.png">

**Comment by ChessGeekBoy** [comment]
I'll fix those bugs, I may or may not have assigned an object of type `Coordinate` to a 
`number`.
